[package]
name = "kernel"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "kernel"
test = false
bench = false

[dependencies]
limine = "0.1.9"
spin = "0.9"
x86_64 = "0.14.10"
bit_field = "0.10.1"


[dependencies.lazy_static]     
version = "1.4.0"
features = ["spin_no_std"]
